/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronted;

import Backend.Cliente;
import Backend.Consultas.ClienteConsulta;
import Backend.Consultas.ProductoConsultas;
import Backend.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author goldtux
 */
public class ClienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProductoGUI
     */
    public ClienteGUI() {
        initComponents();
        eliminarClienteButton.setEnabled(false);
        modificarClienteButton.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        crearClienteButton = new javax.swing.JButton();
        modificarClienteButton = new javax.swing.JButton();
        salirClienteButton = new javax.swing.JButton();
        eliminarClienteButton = new javax.swing.JButton();
        nitCrearClienteTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombreCrearClienteTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        creditoCrearClienteTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telefonoCrearClienteTextField = new javax.swing.JTextField();
        correoCrearClienteTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dpiCrearClienteTextField = new javax.swing.JTextField();
        seleccionarClienteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clienteListajTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        crearClienteButton.setText("Crear");
        crearClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteButtonActionPerformed(evt);
            }
        });

        modificarClienteButton.setText("Modificar");
        modificarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarClienteButtonActionPerformed(evt);
            }
        });

        salirClienteButton.setText("Salir");
        salirClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirClienteButtonActionPerformed(evt);
            }
        });

        eliminarClienteButton.setText("Eliminar");
        eliminarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClienteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("NIT");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Credito:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Correo:");

        jLabel8.setText("DPI:");

        seleccionarClienteButton.setText("Seleccionar");
        seleccionarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonoCrearClienteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(nombreCrearClienteTextField)
                            .addComponent(nitCrearClienteTextField)
                            .addComponent(creditoCrearClienteTextField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(crearClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seleccionarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpiCrearClienteTextField)
                            .addComponent(correoCrearClienteTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(eliminarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modificarClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(salirClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(correoCrearClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dpiCrearClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salirClienteButton)
                            .addComponent(crearClienteButton)
                            .addComponent(modificarClienteButton)
                            .addComponent(eliminarClienteButton)
                            .addComponent(seleccionarClienteButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nitCrearClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreCrearClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(telefonoCrearClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(creditoCrearClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        clienteListajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Fabricante", "Cantidad", "Precio", "Tienda", "Garantia", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(clienteListajTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteButtonActionPerformed
        crear();
        ListarCliente(clienteListajTable);
        limpiarTextBox();
    }//GEN-LAST:event_crearClienteButtonActionPerformed

    private void modificarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarClienteButtonActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Seguro que desea MODIFICAR este registro?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            modificar();
            ListarCliente(clienteListajTable);
            nitCrearClienteTextField.setEnabled(true);
            crearClienteButton.setEnabled(true);
            salirClienteButton.setEnabled(true);
            limpiarTextBox();
        } else {
            nitCrearClienteTextField.setEnabled(true);
            crearClienteButton.setEnabled(true);
            salirClienteButton.setEnabled(true);
            eliminarClienteButton.setEnabled(false);
            modificarClienteButton.setEnabled(false);
            limpiarTextBox();
        }

    }//GEN-LAST:event_modificarClienteButtonActionPerformed

    private void salirClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirClienteButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_salirClienteButtonActionPerformed

    private void eliminarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteButtonActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Seguro que desea ELIMINAR este registro?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, clienteConsulta.eliminarCliente(nitCrearClienteTextField.getText()));
            ListarCliente(clienteListajTable);
            crearClienteButton.setEnabled(true);
            salirClienteButton.setEnabled(true);
            nitCrearClienteTextField.setEnabled(true);
            limpiarTextBox();
        } else {
            nitCrearClienteTextField.setEnabled(true);
            crearClienteButton.setEnabled(true);
            salirClienteButton.setEnabled(true);
            eliminarClienteButton.setEnabled(false);
            modificarClienteButton.setEnabled(false);
            limpiarTextBox();
        }

    }//GEN-LAST:event_eliminarClienteButtonActionPerformed

    private void seleccionarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarClienteButtonActionPerformed

        crearClienteButton.setEnabled(false);
        salirClienteButton.setEnabled(false);

        int fila = clienteListajTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debee Seleccionar Una fila..!!");
        } else {
            eliminarClienteButton.setEnabled(true);
            modificarClienteButton.setEnabled(true);

            nitCrearClienteTextField.setEnabled(false);
            String codigo = (String) clienteListajTable.getValueAt(fila, 0);
            String nombre = (String) clienteListajTable.getValueAt(fila, 1);
            String telefono = (String) clienteListajTable.getValueAt(fila, 2);
            int credito = Integer.parseInt((String) clienteListajTable.getValueAt(fila, 3).toString());
            String correo = (String) clienteListajTable.getValueAt(fila, 4);
            int DPI = Integer.parseInt((String) clienteListajTable.getValueAt(fila, 5).toString());

            nitCrearClienteTextField.setText(codigo);
            nombreCrearClienteTextField.setText(nombre);
            telefonoCrearClienteTextField.setText(telefono);
            creditoCrearClienteTextField.setText("" + credito);
            correoCrearClienteTextField.setText(correo);
            dpiCrearClienteTextField.setText(""+DPI);

        }
    }//GEN-LAST:event_seleccionarClienteButtonActionPerformed
    
    ClienteGUI clienteGUI=new ClienteGUI();
    Cliente cliente=new Cliente();

    public void crear() {

        int reply = JOptionPane.showConfirmDialog(null, "Los datos de cada campo son correctos?", "Confirmacion", JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            String codigo = nitCrearClienteTextField.getText();
            String nombre = nombreCrearClienteTextField.getText();
            String telefono = telefonoCrearClienteTextField.getText();
            int credito = Integer.parseInt(creditoCrearClienteTextField.getText());
            String correo = dpiCrearClienteTextField.getText();
            int dpi = Integer.parseInt(creditoCrearClienteTextField.getText());

            cliente.setCodigoCliente(codigo);
            cliente.setNombre(nombre);
            cliente.setTelefono(telefono);
            cliente.setCredito(credito);
            cliente.setCorreo(correo);
            cliente.setDpi(dpi);


            JOptionPane.showMessageDialog(this, clienteConsulta.crearCliente(cliente));
            limpiarTextBox();

        } else {

        }

    }

    public void modificar() {

    String codigo = nitCrearClienteTextField.getText();
            String nombre = nombreCrearClienteTextField.getText();
            String telefono = telefonoCrearClienteTextField.getText();
            int credito = Integer.parseInt(creditoCrearClienteTextField.getText());
            String correo = dpiCrearClienteTextField.getText();
            int dpi = Integer.parseInt(creditoCrearClienteTextField.getText());

            cliente.setCodigoCliente(codigo);
            cliente.setNombre(nombre);
            cliente.setTelefono(telefono);
            cliente.setCredito(credito);
            cliente.setCorreo(correo);
            cliente.setDpi(dpi);;


        JOptionPane.showMessageDialog(this, clienteConsulta.modificarCliente(cliente));

    }

    public void limpiarTextBox() {
        nitCrearClienteTextField.setText("");
        nombreCrearClienteTextField.setText("");
        telefonoCrearClienteTextField.setText("");
        creditoCrearClienteTextField.setText("");
        correoCrearClienteTextField.setText("");
        dpiCrearClienteTextField.setText("");

    }

    ClienteConsulta clienteConsulta=new ClienteConsulta();


    DefaultTableModel tableModel = new DefaultTableModel();

    public void ListarCliente(JTable tablaProductos) {
        limpiarTabla(tablaProductos);

        tableModel = (DefaultTableModel) tablaProductos.getModel();

        List<Producto> listaProductos = clienteConsulta.Listar();
        Object[] object = new Object[8];

        for (int i = 0; i < listaProductos.size(); i++) {
            object[0] = listaProductos.get(i).getCodigoProducto();
            object[1] = listaProductos.get(i).getNombre();
            object[2] = listaProductos.get(i).getFabricante();
            object[3] = listaProductos.get(i).getCantidad();
            object[4] = listaProductos.get(i).getPrecio();
            object[5] = listaProductos.get(i).getTienda();
            object[6] = listaProductos.get(i).getGarantia();
            object[7] = listaProductos.get(i).getDescripcion();
            tableModel.addRow(object);

        }
        clienteListajTable.setModel(tableModel);

    }

    public void limpiarTabla(JTable Jtable) {
        DefaultTableModel tb = (DefaultTableModel) Jtable.getModel();
        int a = Jtable.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clienteListajTable;
    private javax.swing.JTextField correoCrearClienteTextField;
    private javax.swing.JButton crearClienteButton;
    private javax.swing.JTextField creditoCrearClienteTextField;
    private javax.swing.JTextField dpiCrearClienteTextField;
    private javax.swing.JButton eliminarClienteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarClienteButton;
    private javax.swing.JTextField nitCrearClienteTextField;
    private javax.swing.JTextField nombreCrearClienteTextField;
    private javax.swing.JButton salirClienteButton;
    private javax.swing.JButton seleccionarClienteButton;
    private javax.swing.JTextField telefonoCrearClienteTextField;
    // End of variables declaration//GEN-END:variables
}
