/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronted;

import Backend.Consultas.ProductoConsultas;
import Backend.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author goldtux
 */
public class ProductoGUI extends javax.swing.JFrame {

    TrabajadorGUI trabajadorGUI = new TrabajadorGUI();

    /**
     * Creates new form ProductoGUI
     */
    public ProductoGUI() {
        initComponents();
        eliminarProductoButton.setEnabled(false);
        modificarProductoButton.setEnabled(false);
        trabajadorGUI.ListarProducto(productosListajTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        crearProductoButton = new javax.swing.JButton();
        modificarProductoButton = new javax.swing.JButton();
        salirProductoButton = new javax.swing.JButton();
        eliminarProductoButton = new javax.swing.JButton();
        codigoCrearProductoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombreCrearProductoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cantidadCrearProductoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fabricanteCrearProductoTextField = new javax.swing.JTextField();
        precioCrearProductoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        garantiaCrearProductoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        descripcionCrearProductoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tiendaCrearProductoTextField = new javax.swing.JTextField();
        seleccionarProductoButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosListajTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Producto");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        crearProductoButton.setText("Crear");
        crearProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProductoButtonActionPerformed(evt);
            }
        });

        modificarProductoButton.setText("Modificar");
        modificarProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductoButtonActionPerformed(evt);
            }
        });

        salirProductoButton.setText("Salir");
        salirProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirProductoButtonActionPerformed(evt);
            }
        });

        eliminarProductoButton.setText("Eliminar");
        eliminarProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Fabricante:");

        jLabel5.setText("Precio:");

        jLabel6.setText("Garantia:");

        jLabel7.setText("Descripcion");

        jLabel8.setText("Tienda:");

        seleccionarProductoButton.setText("Seleccionar");
        seleccionarProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarProductoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fabricanteCrearProductoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(nombreCrearProductoTextField)
                            .addComponent(codigoCrearProductoTextField)
                            .addComponent(cantidadCrearProductoTextField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(crearProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seleccionarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionCrearProductoTextField)
                            .addComponent(garantiaCrearProductoTextField)
                            .addComponent(tiendaCrearProductoTextField)
                            .addComponent(precioCrearProductoTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(eliminarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modificarProductoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(salirProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(precioCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tiendaCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(garantiaCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(descripcionCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salirProductoButton)
                            .addComponent(crearProductoButton)
                            .addComponent(modificarProductoButton)
                            .addComponent(eliminarProductoButton)
                            .addComponent(seleccionarProductoButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codigoCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fabricanteCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cantidadCrearProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        productosListajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Fabricante", "Cantidad", "Precio", "Tienda", "Garantia", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(productosListajTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoButtonActionPerformed
        crear();
        trabajadorGUI.ListarProducto(productosListajTable);
        limpiarTextBox();
    }//GEN-LAST:event_crearProductoButtonActionPerformed

    private void modificarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductoButtonActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Seguro que desea MODIFICAR este registro?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            modificar();
            trabajadorGUI.ListarProducto(productosListajTable);
            codigoCrearProductoTextField.setEnabled(true);
            crearProductoButton.setEnabled(true);
            salirProductoButton.setEnabled(true);
            limpiarTextBox();
        } else {
            codigoCrearProductoTextField.setEnabled(true);
            crearProductoButton.setEnabled(true);
            salirProductoButton.setEnabled(true);
            limpiarTextBox();
        }

    }//GEN-LAST:event_modificarProductoButtonActionPerformed

    private void salirProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirProductoButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_salirProductoButtonActionPerformed

    private void eliminarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoButtonActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Seguro que desea ELIMINAR este registro?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, productoConsultas.eliminarProducto(codigoCrearProductoTextField.getText()));
            trabajadorGUI.ListarProducto(productosListajTable);
            crearProductoButton.setEnabled(true);
            salirProductoButton.setEnabled(true);
            codigoCrearProductoTextField.setEnabled(true);
            limpiarTextBox();
        } else {
            codigoCrearProductoTextField.setEnabled(true);
            crearProductoButton.setEnabled(true);
            salirProductoButton.setEnabled(true);
            limpiarTextBox();
        }

    }//GEN-LAST:event_eliminarProductoButtonActionPerformed

    private void seleccionarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarProductoButtonActionPerformed

        crearProductoButton.setEnabled(false);
        salirProductoButton.setEnabled(false);

        int fila = productosListajTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debee Seleccionar Una fila..!!");
        } else {
            eliminarProductoButton.setEnabled(true);
            modificarProductoButton.setEnabled(true);

            codigoCrearProductoTextField.setEnabled(false);
            String codigo = (String) productosListajTable.getValueAt(fila, 0);
            String nombre = (String) productosListajTable.getValueAt(fila, 1);
            String fabricante = (String) productosListajTable.getValueAt(fila, 2);
            int cantidad = Integer.parseInt((String) productosListajTable.getValueAt(fila, 3).toString());
            double precio = Double.parseDouble((String) productosListajTable.getValueAt(fila, 4).toString());
            String codigoTienda = (String) productosListajTable.getValueAt(fila, 5);
            int garantia = Integer.parseInt((String) productosListajTable.getValueAt(fila, 6).toString());
            String descripcion = (String) productosListajTable.getValueAt(fila, 7);

            codigoCrearProductoTextField.setText(codigo);
            nombreCrearProductoTextField.setText(nombre);
            fabricanteCrearProductoTextField.setText(fabricante);
            cantidadCrearProductoTextField.setText("" + cantidad);
            precioCrearProductoTextField.setText("" + precio);
            tiendaCrearProductoTextField.setText(codigoTienda);
            garantiaCrearProductoTextField.setText("" + garantia);
            descripcionCrearProductoTextField.setText(descripcion);
        }
    }//GEN-LAST:event_seleccionarProductoButtonActionPerformed
    ProductoConsultas productoConsultas = new ProductoConsultas();
    Producto producto = new Producto();

    public void crear() {

        int reply = JOptionPane.showConfirmDialog(null, "Los datos de cada campo son correctos?", "Confirmacion", JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            String codigo = codigoCrearProductoTextField.getText();
            String nombre = nombreCrearProductoTextField.getText();
            String fabricante = fabricanteCrearProductoTextField.getText();
            int cantidad = Integer.parseInt(cantidadCrearProductoTextField.getText());
            double precio = Double.parseDouble(precioCrearProductoTextField.getText());
            String codigoTienda = tiendaCrearProductoTextField.getText();
            int garantia = Integer.parseInt(garantiaCrearProductoTextField.getText());
            String descripcion = descripcionCrearProductoTextField.getText();

            producto.setCodigoProducto(codigo);
            producto.setNombre(nombre);
            producto.setFabricante(fabricante);
            producto.setCantidad(cantidad);
            producto.setPrecio(precio);
            producto.setTienda(codigoTienda);
            producto.setGarantia(garantia);
            producto.setDescripcion(descripcion);

            JOptionPane.showMessageDialog(this, productoConsultas.crearProducto(producto));
            limpiarTextBox();

        } else {

        }

    }

    public void modificar() {

        String codigo = codigoCrearProductoTextField.getText();
        String nombre = nombreCrearProductoTextField.getText();
        String fabricante = fabricanteCrearProductoTextField.getText();
        int cantidad = Integer.parseInt(cantidadCrearProductoTextField.getText());
        double precio = Double.parseDouble(precioCrearProductoTextField.getText());
        String codigoTienda = tiendaCrearProductoTextField.getText();
        int garantia = Integer.parseInt(garantiaCrearProductoTextField.getText());
        String descripcion = descripcionCrearProductoTextField.getText();

        producto.setCodigoProducto(codigo);
        producto.setNombre(nombre);
        producto.setFabricante(fabricante);
        producto.setCantidad(cantidad);
        producto.setPrecio(precio);
        producto.setTienda(codigoTienda);
        producto.setGarantia(garantia);
        producto.setDescripcion(descripcion);

        JOptionPane.showMessageDialog(this, productoConsultas.modificarProducto(producto));

    }

    public void limpiarTextBox() {
        codigoCrearProductoTextField.setText("");
        nombreCrearProductoTextField.setText("");
        fabricanteCrearProductoTextField.setText("");
        cantidadCrearProductoTextField.setText("");
        precioCrearProductoTextField.setText("");
        tiendaCrearProductoTextField.setText("");
        garantiaCrearProductoTextField.setText("");
        descripcionCrearProductoTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cantidadCrearProductoTextField;
    public javax.swing.JTextField codigoCrearProductoTextField;
    public javax.swing.JButton crearProductoButton;
    public javax.swing.JTextField descripcionCrearProductoTextField;
    public javax.swing.JButton eliminarProductoButton;
    public javax.swing.JTextField fabricanteCrearProductoTextField;
    public javax.swing.JTextField garantiaCrearProductoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton modificarProductoButton;
    public javax.swing.JTextField nombreCrearProductoTextField;
    public javax.swing.JTextField precioCrearProductoTextField;
    public javax.swing.JTable productosListajTable;
    public javax.swing.JButton salirProductoButton;
    public javax.swing.JButton seleccionarProductoButton;
    public javax.swing.JTextField tiendaCrearProductoTextField;
    // End of variables declaration//GEN-END:variables
}
